### ISSUE TITLE
Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by andrzej-casper** [CasperDash/useWallet#80]
I wanted to use signing functionality, and created the following React app:

```typescript
import {
  CasperDashConnector,
  CasperSignerConnector,
  CasperProvider,
  createClient,
  useSign
} from '@casperdash/usewallet';

const client = createClient({
  connectors: [new CasperSignerConnector(), new CasperDashConnector()],
  autoConnect: true,
});

function App() {
  const { sign } = useSign({
    deploy: {
      deploy: null,
    },
    signingPublicKeyHex: 'abc',
    targetPublicKeyHex: 'abcde',
  });

  return (
    <CasperProvider client={client}>
      <button onClick={() => sign()}>Sign with CasperDash</button>
    </CasperProvider>
  )
}

export default App;
```

Page crashes with the following error:

```
Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (QueryClientProvider.tsx:49:1)
    at useMutation (useMutation.ts:66:1)
    at useSign (useSign.ts:49:1)
    at App (App.tsx:15:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

**Comment by hoailinh1210** [comment]
Hi @andrzej-casper , do you use version 1.0.1?

**Comment by hoailinh1210** [comment]
Hi @andrzej-casper , useSign should wrap by CasperProvider component, so you should split up to component as children, you can take a look on our example, so it should be:

```
import {
  CasperDashConnector,
  CasperSignerConnector,
  CasperProvider,
  createClient,
  useSign
} from '@casperdash/usewallet';

const client = createClient({
  connectors: [new CasperSignerConnector(), new CasperDashConnector()],
  autoConnect: true,
});

function App() {
  return (
    <CasperProvider client={client}>
      <SignComponent />
    </CasperProvider>
  )
}

export default App;
```

```
function SignComponent() {
   const { sign } = useSign({
    deploy: {
      deploy: null,
    },
    signingPublicKeyHex: 'abc',
    targetPublicKeyHex: 'abcde',
  });

  return (
    <div>
      <button onClick={() => sign()}>Sign with CasperDash</button>
    </div>

  )
}
```

**Comment by hoailinh1210** [comment]
Another, we also have example for this, I think you can base on this for the first time

- Without ledger example:
https://github.com/CasperDash/useWallet/tree/main/examples/example-react-not-ledger

- Full example
https://github.com/CasperDash/useWallet/tree/main/examples/example-react

**Comment by hoailinh1210** [comment]
You can reference my example and it is react context so we will need to wrap it and use useSign in children.
